name: Configure Ai21 Api Key

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: set api key as env variable
      env:
        API_KEY: ${{ secrets.AI21_API_KEY }}
